[ODRP-345] Removed 'coverageEnabled'.
The presence of `coverageEnabled` in `build.sbt` caused problems in the deployment to QA:

```
java.io.FileNotFoundException: /home/jenkins/workspace/Digital Platform Reporting Service (DPRS)/dprs/target/scoverage-data/scoverage.measurements.c143a95b-351b-456e-9280-56322da9f748.1 (No such file or directory)
```

It turns out that it wasn't necessary, after all.